apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 5Gi  # 5GB of storage for MySQL
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # Retain PV after PVC is deleted
  storageClassName: manual
  hostPath:
    path: /mnt/data/mysql  # Path to the directory in the node's filesystem
